### ISSUE TITLE
Add importers for dataset

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/NGMT#10]
Hello @rmndrs89,

could you pull the new dataclass structure and update your dataset function (maybe first for keepcontrol) [here](ngmt/datasets/keepcontrol.py).

It should work that data is then importet into these new dataclasses. Next I would like to see if the events @masoudabedinifar is detecting can be incoperated in the EventData using his translated algorithms.

**Comment by rmndrs89** [comment]
Completed importer for keepcontrol dataset to load data into MotionData object, see [28c6d94c6dc4203ba8a15795dff465994a26d31b](28c6d94c6dc4203ba8a15795dff465994a26d31b)
