### ISSUE TITLE
Brush up documentation

### ISSUE THREAD

**Issue by rmndrs89** [neurogeriatricskiel/NGMT#12]
Hi @JuliusWelzel and @masoudabedinifar ,

let us keep in mind that we need to start writing documentation for the code as well, and preferably one that visually depicts the dataset, algorithms, and pipelines, and where they live,

Best regards,
Robbin

**Comment by JuliusWelzel** [comment]
Discuss solution as implemented in https://github.com/neurogeriatricskiel/NGMT/issues/17.

**Comment by JuliusWelzel** [comment]
# improve documentation

For this we should have:

- [ ] Example notebook for a single dataset with GSD algorithm
- [ ] Visualisation of raw data and events
- [ ] Draft of full documentation of all functions
- [ ] Draft of install instruction
- [ ] Implement test for dataclasses
- [ ] Implement test on poetry
- [ ] Set up `pyproject`

**Comment by masoudabedinifar** [comment]
Hi @rmndrs89 and @JuliusWelzel,

I just updated tests for the low-level functions of the GSD algorithm in a new branch (tes-dev) and I am sharing it with you. 
It's a first draft and I will update it based on your feedback. You may also change the location and name of the test if needed.
[(https://github.com/neurogeriatricskiel/NGMT/blob/test-dev/ngmt/test/test_calc.py)]

Best,
Masoud.

**Comment by JuliusWelzel** [comment]
Hi, I added automatic testing on GH actions as well as the code coverage
