### ISSUE TITLE
Adapt algorithms to the work on the dataclasses

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/NGMT#21]
As discussed, we should hand our own data classes to the functions @masoud translated.

Anyone has comments on this?

**Comment by rmndrs89** [comment]
In principle the data loaders should just return an instance of a `MotionData` object. In the first lines of the main loop, the user should then extract the relevant sensor data. In our case this is the acceleration data from the lower back. In pseudo-code that would look like:

```python
motion_data = some_dataset.load_file(file_name)  # MotionData object

# Loop over the list of recordings
for idx, recording_data in enumerate(motion_data.data):
    sampling_frequency = recording_data.sampling_frequency

    # Extract acceleration from the lower back sensor
    lower_back_acc = ...
```

**Comment by JuliusWelzel** [comment]
I think it depends if an importer returns a `RecordingData` or `MotionData` class. But in general, it should work that way.

**Comment by rmndrs89** [comment]
Works for now as expected!
