### ISSUE TITLE
Make colors consistent

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/NGMT#22]
To make it easier to follow the documentation, we should have consistent colors representing similar data.

Any comments on which colormap we should be using? I would propose the [sequential  `plasma`](https://matplotlib.org/stable/users/explain/colors/colormaps.html#sequential) colormap.

**Comment by masoudabedinifar** [comment]
Hello @JuliusWelzel,

I will take care of the color consistency using [(https://matplotlib.org/stable/users/explain/colors/colormaps.html#sequential)].

Best, 
Masoud.

**Comment by JuliusWelzel** [comment]
@masoudabedinifar I included a [`config.py`](https://github.com/neurogeriatricskiel/NGMT/blob/c23d385e3191ece132b733940f86a5202b6cb67e/ngmt/config.py#L8) with a dict and colors.

You can load the colors in any script like:
```python
from ngmt.config import cfg_colors

# use colors
colors = cfg_colors['raw']
```

Please adapt this in all of your plotting :) Thanks

**Comment by masoudabedinifar** [comment]
@JuliusWelzel I updated the figure's colors and I will use the same manner in the future.: 872a37ee926d1c7fc30fc778210e727d762fb577
