### ISSUE TITLE
Update the Mobilise-D function to return a dataclass object

### ISSUE THREAD

**Issue by rmndrs89** [neurogeriatricskiel/NGMT#23]
We need to update the [load_file](https://github.com/neurogeriatricskiel/NGMT/blob/9f3d05c979de8121c3e240d808392d8fec5e398f/ngmt/datasets/mobilised.py#L27) function for the Mobilise-D as it does not output the latest version of the dataclass as discussed.

**Comment by rmndrs89** [comment]
@masoudabedinifar can you check if it now works as expected, so that you can finish the example notebook? If it does not work, can you provide some feedback and lines of code so that I can reproduce the error?

If it works, you can close the issue with comment ;)

**Comment by masoudabedinifar** [comment]
Hello @rmndrs89,

Thanks, it works and I can load my data without any errors. I am going to close the issue.

Kind regards,
Masoud.
