### ISSUE TITLE
Option for event output in BIDS format

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/NGMT#34]
The toolbox should contain the option output detected events in a BIDS like manner

**Comment by rmndrs89** [comment]
I will commit and @JuliusWelzel will check. @JuliusWelzel will try the BIDS validator, or send @rmndrs89 the instructions for this.

**Comment by JuliusWelzel** [comment]
Done in https://github.com/neurogeriatricskiel/NGMT/commit/4f32709795d6e79fdaa1df5579b6ee5f7658a8bb
