### ISSUE TITLE
Requirements of Journal of Open Source Software (JOSS) for Publishing Toolbox

### ISSUE THREAD

**Issue by masoudabedinifar** [neurogeriatricskiel/NGMT#38]
Dear all,

Submission requirements for the Journal of Open Source Software [JOSS](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) are as follows:

- [x] It should be fully featured research code.
- [x] The toolbox should be released under an [OSI-approved license](https://opensource.org/licenses).
- [x] The toolbox should have well-written documentation.
- [x] The toolbox should have well-written tests.
- [x] The software must be open source as per the [OSI definition](https://opensource.org/osd).
- [x] The software must be hosted at a location where users can open issues and propose code changes without manual approval of (or payment for) accounts.
- [x] The software must have an obvious research application.
- [x] You must be a major contributor to the software you are submitting, and have a GitHub account to participate in the review process.
- [x] Your paper must not focus on new research results accomplished with the software.
- [x] Your paper (paper.md and BibTeX files, plus any figures) must be hosted in a Git-based repository together with your software (although they may be in a short-lived branch that is never merged with the default).
- [x] Be stored in a repository that can be cloned without registration.
- [x] Be stored in a repository that is browsable online without registration.
- [x] Have an issue tracker that is readable without registration.
- [x] Permit individuals to create issues/file tickets against your repository.
- [x] Make release 0.0.4 for publications

**Comment by rmndrs89** [comment]
Hi @masoudabedinifar,

very cool, thanks for organizing this. Could you maybe tick off the items that have already been addressed? We can then plan ahead with whatever still needs to be addressed.

BR

**Comment by JuliusWelzel** [comment]
Hello there, thanks for your submission to JOSS.
Your paper, 'NGMT: NeuroGeriatric Motion Toolbox - An Open-Source Python Toolbox for Analyzing Neurological Motion Data from Various Recording Modalities', is currently awaiting triage by our managing editor. This generally takes up to a week, but during busy times can take a number of weeks. Until then, your paper won't show up in the https://github.com/openjournals/joss-reviews repository.
You can view the latest status of your paper here: https://joss.theoj.org/papers/206544a8549ddb295d0fbbd1fc898b3f
Many thanks
The JOSS editorial robot.
