### ISSUE TITLE
Merge branch to the main branch

### ISSUE THREAD

**Issue by masoudabedinifar** [neurogeriatricskiel/NGMT#41]
Dear @JuliusWelzel ,

Could you kindly merge the 'module-masoud' into the main branch? As per our discussion in the algorithm meeting, I will create a new branch for developing or improving other algorithms accordingly. In module-masoud, all algorithms were re-organaized and updated based on new suggestions.

Thank you.

Best regards,
Masoud.

**Comment by JuliusWelzel** [comment]
Sure, I did that. For the future, could you just open a PR? Thanks

**Comment by JuliusWelzel** [comment]
Done in 1a6113debcbf7dad7ad3fa7a3164872802882747
