### ISSUE TITLE
Documentation fails

### ISSUE THREAD

**Issue by masoudabedinifar** [neurogeriatricskiel/NGMT#44]
Dear @JuliusWelzel 

I have updated modules and examples in the main branch. However, the documentation wasn't automatically added. Could you please check the documentation?

Thanks,

Best wishes,
Masoud.

**Comment by JuliusWelzel** [comment]
Hi, they are online now [here](https://neurogeriatricskiel.github.io/NGMT/examples/). Please check from this commit ad6aeeab6d1233d868e16b2606f4e3433122a957

**Comment by JuliusWelzel** [comment]
All example incoperated
