### ISSUE TITLE
Fix documentation for datasets

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/NGMT#48]
The documentation for the datasets does not render correctly:
https://neurogeriatricskiel.github.io/NGMT/datasets/

The Parameters and Returns do not seem to be specified correctly.
@rmndrs89, could you please fix this?

**Comment by JuliusWelzel** [comment]
@masoudabedinifar is taking over because of holidays

**Comment by JuliusWelzel** [comment]
Hi, the SSD examples do not seem to render correctly
![image](https://github.com/neurogeriatricskiel/NGMT/assets/52565341/b80d3a41-9421-49e9-934a-f92e4f906f1f)

and so is the dataset doc not working:
![image](https://github.com/neurogeriatricskiel/NGMT/assets/52565341/60aaa41b-e3d0-40d9-8a36-6b2c17414b2b)


Please make sure they follow GoogleStyle DocStrings

**Comment by masoudabedinifar** [comment]
@JuliusWelzel docstrings were updated in this commit and the problem is solved: 46ab62984aef24e452ff4d783113e0665ad7cd62
