### ISSUE TITLE
Add datetime to gait sequences detection

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/NGMT#51]
I have running the GSD module for home data.
When analysing, I became apparent, that having the original datetime information in the output would be useful. @masoudabedinifar Is there an option to implement this?

Best would be to have a onset in datetime format as optional input to the function [here](https://github.com/neurogeriatricskiel/NGMT/blob/a269fda651e8558166902b42b4312892b9eda8ba/ngmt/modules/gsd/_paraschiv.py#L335).

**Comment by masoudabedinifar** [comment]
I tried to organize the GSD algorithm as suggested here: 5eb13b0aabfdcadc1dc6395272dcd9f16ff8c186. The algorithm's output will use the original datetime if it is available. Could you please check if it works?
Thanks!

Best,
Masoud.

**Comment by JuliusWelzel** [comment]
I reworked this in https://github.com/neurogeriatricskiel/NGMT/commit/6ec908b913cfd95de29d656e19b0b121041bc2f2. dt_data is now a separate pd.Series as datetime input

**Comment by JuliusWelzel** [comment]
Finalized all checks in https://github.com/neurogeriatricskiel/NGMT/commit/ad102772fd355e6ca64f7ad6a00a4c95d066a1d6.
