### ISSUE TITLE
Add importers for most common devices

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/NGMT#63]
I want to add more importers for commonly used devices here:
['ngmt/utils/importers.py'](https://github.com/neurogeriatricskiel/NGMT/blob/main/ngmt/utils/importers.py)

Currently, there are only two. @hansencl and @rmndrs89, please name the most common ones (3-4) and provide some example data so I can write the importers. Cheers :)

**Comment by rmndrs89** [comment]
Optical motion capture
- [ ] Vicon
- [ ] Qualisys

Inertial measurement units
- [ ] Axivity
- [ ] Noraxon
- [ ] Movesense
- [ ] XSens
- [ ] Physilog
- [ ] Mbientlab
- [ ] APDM Mobility Lab

**Comment by JuliusWelzel** [comment]
Thanks, @rmndrs89. Do we have example data for all of them? I indicated this, where I know we have raw data avaliable

**Comment by JuliusWelzel** [comment]
CLosing this now, I would open new issues for a single importer when needed. @rmndrs89, agreed?
