### ISSUE TITLE
GSD error

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/NGMT#64]
@masoudabedinifar could you check why my example in https://github.com/neurogeriatricskiel/NGMT/blob/main/examples/06_tutorial_lowlevel_import.ipynb throws an error? Thanks

**Comment by masoudabedinifar** [comment]
Hi @JuliusWelzel 
I've resolved the error in this commit: 44e028ae157859847b526648bbbd5fd8ca08745e. 
If there are no further additions to the example, you may close the issue as it has been resolved.
Thanks!

**Comment by JuliusWelzel** [comment]
Closing for example in favour of https://github.com/neurogeriatricskiel/NGMT/issues/65
