### ISSUE TITLE
Accelerometer unit conversion for physical activity monitoring

### ISSUE THREAD

**Issue by rmndrs89** [neurogeriatricskiel/NGMT#67]
Hi @masoudabedinifar ,

https://github.com/neurogeriatricskiel/NGMT/blob/7153c57ad80d46be22f971f1103cb15b2d0968e9/ngmt/modules/pam/_pam.py#L123

Why is this hard-coded in the algorithm? What happens if the accelerometer data are already in g?
Should this not be checked using the channels information?

Best regards,
Robbin

**Comment by masoudabedinifar** [comment]
The issue is closed since it was mentioned in an organized way in here [Issues regarding PhysicalActivityMonitoring algorithm](https://github.com/neurogeriatricskiel/NGMT/issues/73).
