### ISSUE TITLE
Vertical acceleration

### ISSUE THREAD

**Issue by rmndrs89** [neurogeriatricskiel/NGMT#69]
Hi @masoudabedinifar, @JuliusWelzel,

https://github.com/neurogeriatricskiel/NGMT/blob/7153c57ad80d46be22f971f1103cb15b2d0968e9/ngmt/modules/icd/_paraschiv.py#L110

Are we sure that the tracked point is always "LowerBack" and that the "x" component always corresponds to the vertical acceleration? Or should we try to avoid hard-coding this in the initial contact detection algorithm?

Should we think of putting all data in the same orientation and having anatomical frames for that, see e.g., [https://gaitmap.readthedocs.io/en/latest/source/user_guide/coordinate_systems.html](https://gaitmap.readthedocs.io/en/latest/source/user_guide/coordinate_systems.html)

Best regards,
Robbin

**Comment by masoudabedinifar** [comment]
The issue is closed since it is mentioned in an organized way in [Issues regarding ICD algorithm](https://github.com/neurogeriatricskiel/NGMT/issues/71)
