### ISSUE TITLE
Issues regarding GSD algorithm

### ISSUE THREAD

**Issue by masoudabedinifar** [neurogeriatricskiel/NGMT#70]
Dear all,

The issues that need to be addressed regarding the [GSD](https://github.com/neurogeriatricskiel/NGMT/blob/main/ngmt/modules/gsd/_paraschiv.py) algorithm before submitting the JOSS paper could be listed as follows:

1. **Error handling for the cases such as [KeepControl][https://github.com/neurogeriatricskiel/NGMT/issues/66]** 

- [x] Add error handling inside the algorithm to manage cases where there are fewer than 5 steps identified as gait sequences (such as tug data from KeepControl). Provide an error message such as: "Gait sequence(s) were not detected since there are not enough steps."

2.  **Attribute match [Docs GSD](https://github.com/neurogeriatricskiel/NGMT/issues/72)**

- [x] The attributes in the docstring and init function do not match as mentioned here [Attributes](https://github.com/neurogeriatricskiel/NGMT/blob/2cec3d5dae190a34b13fba92e25649f121204b73/ngmt/modules/gsd/_paraschiv.py#L38)

3.  **Improvement should be done for GSD for the situations where we have less than 5 steps in the data such TUG from KeepControl dataset to handle them**

- [x] Handling cases such as [KeepControl][https://github.com/neurogeriatricskiel/NGMT/issues/66]

**Comment by masoudabedinifar** [comment]
The cases where there are fewer than 5 steps in the data are handled by popping up the error message: "No gait sequences detected due to insufficient steps in the data" with commit: feb4ca3f3d7b8c3fa1854a9788c7f638ea3ea8ba

**Comment by masoudabedinifar** [comment]
2. Attribute now matches with init by commit: 913c7bf03aa2142e034bf81f254f05f8d3f92da1

**Comment by masoudabedinifar** [comment]
Issues were handled and closed.

**Comment by rmndrs89** [comment]
I have completed the third task, and therefore close this issue.
