### ISSUE TITLE
Issues regarding ICD algorithm

### ISSUE THREAD

**Issue by masoudabedinifar** [neurogeriatricskiel/NGMT#71]
Dear all,

The issues that need to be addressed regarding the [ICD](https://github.com/neurogeriatricskiel/NGMT/blob/main/ngmt/modules/icd/_paraschiv.py) algorithm before submitting the JOSS paper could be listed as follows:

1. **Add dt_data as an optional input to the ICD algorithm as we did in [GSD](https://github.com/neurogeriatricskiel/NGMT/blob/main/ngmt/modules/gsd/_paraschiv.py)** 

- [x]  We need to incorporate "dt_data" into the ICD algorithm to provide real-time information whenever it's available and given as an input to the algorithm. The onset should be updated accordingly.

2. **Error handling for the cases such as [KeepControl][https://github.com/neurogeriatricskiel/NGMT/issues/66]** 

- [x] Since the GSD algorithm requires at least 5 consecutive steps to detect the event as a gait sequence, the algorithm fails to identify the gait sequence for this special case. However, still we can apply ICD to the referred data. The issue should be solved in a way that 'gait_sequences' in https://github.com/neurogeriatricskiel/NGMT/blob/main/ngmt/modules/icd/_paraschiv.py should be optional. 
For this purpose, we need to change the algorithm in the following way. When 'gait_sequences' are not provided, the ICD should create artificial gait sequences that cover the active parts of the data and then identify initial contacts within defined limits.

3. **Vertical acceleration assignment [Vertical acceleration][https://github.com/neurogeriatricskiel/NGMT/issues/69]** 
- [x] We should try to avoid hard-coding of "acc_vertical = data["LowerBack_ACCEL_x"]" in the initial contact detection algorithm and use some methods to detect x component of the acceleration and then use it inside the algorithm to detect initial contacts.

**Comment by rmndrs89** [comment]
I have completed tasks 2 and 3. @JuliusWelzel could you transfer the "tracking_systems" and "tracked_points" algorithms for the [GSD](https://github.com/neurogeriatricskiel/NGMT/blob/5dddf74e95e226c1f5e7fcbc8ad612830ecc7e24/ngmt/modules/gsd/_paraschiv.py#L60) and [ICD](https://github.com/neurogeriatricskiel/NGMT/blob/5dddf74e95e226c1f5e7fcbc8ad612830ecc7e24/ngmt/modules/icd/_paraschiv.py#L50) to the detect method as optional arguments??

**Comment by JuliusWelzel** [comment]
Done in https://github.com/neurogeriatricskiel/NGMT/commit/d3dcda1d104fbb24dae23d2b08b6b6463b19e867
