### ISSUE TITLE
Docs GSD

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/NGMT#72]
Hi, the attributes in the docstring and __init__ function do not match here https://github.com/neurogeriatricskiel/NGMT/blob/2cec3d5dae190a34b13fba92e25649f121204b73/ngmt/modules/gsd/_paraschiv.py#L38

@masoudabedinifar, please check. :)

**Comment by masoudabedinifar** [comment]
The issue is closed since it is mentioned here [https://github.com/neurogeriatricskiel/NGMT/issues/70](https://github.com/neurogeriatricskiel/NGMT/issues/70)
