### ISSUE TITLE
Issues regarding PhysicalActivityMonitoring algorithm

### ISSUE THREAD

**Issue by masoudabedinifar** [neurogeriatricskiel/NGMT#73]
Dear all,

The issues that need to be addressed regarding the [PhysicalActivityMonitoring](https://github.com/neurogeriatricskiel/NGMT/blob/main/ngmt/modules/pam/_pam.py) algorithm before submitting the JOSS paper could be listed as follows:

1. **Tracked point for physical activity monitoring** 

- [x]  "Why is this hard-coded? What if I would want to do the analysis for the right side? What if I choose to name my tracked point "leftWrist" and "rightWrist" or "leftHand" and "rightHand"?" as mentioned here [Tracked point for physical activity monitoring](https://github.com/neurogeriatricskiel/NGMT/issues/68)

2. **Accelerometer unit conversion for physical activity monitoring** 

- [x] "Why is this hard-coded in the algorithm? What happens if the accelerometer data are already in g?
Should this not be checked using the channels information?" as mentioned here [Accelerometer unit conversion for physical activity monitoring](https://github.com/neurogeriatricskiel/NGMT/issues/67)

3.  **Change data columns in a general way to apply to any kind of dataset**

- [x] Make this calculation general: [data["en"] = np.linalg.norm(data[["LARM_ACCEL_x", "LARM_ACCEL_y", "LARM_ACCEL_z"]], axis=1)](https://github.com/neurogeriatricskiel/NGMT/blob/main/ngmt/modules/pam/_pam.py#L115)

**Comment by masoudabedinifar** [comment]
Dear all,

The issues that need to be addressed regarding the [PhysicalActivityMonitoring](https://github.com/neurogeriatricskiel/NGMT/blob/main/ngmt/modules/pam/_pam.py) algorithm before submitting the JOSS paper could be listed as follows:

1. **Tracked point for physical activity monitoring** 

- [ ]  "Why is this hard-coded? What if I would want to do the analysis for the right side? What if I choose to name my tracked point "leftWrist" and "rightWrist" or "leftHand" and "rightHand"?" as mentioned here [Tracked point for physical activity monitoring](https://github.com/neurogeriatricskiel/NGMT/issues/68)

2. **Accelerometer unit conversion for physical activity monitoring** 

- [ ] "Why is this hard-coded in the algorithm? What happens if the accelerometer data are already in g?
Should this not be checked using the channels information?" as mentioned here [Accelerometer unit conversion for physical activity monitoring](https://github.com/neurogeriatricskiel/NGMT/issues/67)

3.  **Change data columns in a general way to apply to any kind of dataset**

- [ ]  # Calculate Euclidean Norm (EN) 
        data["en"] = np.linalg.norm(data[["LARM_ACCEL_x", "LARM_ACCEL_y", "LARM_ACCEL_z"]], axis=1)

4. **Defining parameters of the preprocessing steps out of the algorithm** 

- [ ]  Based on discussion in the algorithm dev. meeting, we need to move all parameters (such as order, cutoff_freq_hz, etc.) out of the algorithm and into the def __init__ method to avoid hardcoding. These parameters should include those used in functions such as preprocessing.lowpass_filter.

5. **Convert ENMO from g to milli-g** 

- [ ] The data["enmo"] = data["truncated_enmo"] * 1000 should be done outside of the algorithm itself instead of hardcoding.

**Comment by masoudabedinifar** [comment]
I have addressed all issues in commit: 5c8617c35567cd612606cff67332c3b41024a9d9. Could you please review the changes? If you approve them, then please proceed to close the issues.

**Comment by JuliusWelzel** [comment]
Can you open a PR and ask for a review or point us to the lines we should be reviewing?

**Comment by masoudabedinifar** [comment]
> Can you open a PR and ask for a review or point us to the lines we should be reviewing?

I merged this directly into the main branch with the commit: 5c8617c35567cd612606cff67332c3b41024a9d9. I'm uncertain whether it's possible to create a pull request after pushing the commit. Thank you!"

**Comment by JuliusWelzel** [comment]
I have reviewed the code. Looks good, only mean calculation is optimized in  https://github.com/neurogeriatricskiel/NGMT/commit/4b609f031bf496dcc113da624cd8cd56963f90cd

**Comment by JuliusWelzel** [comment]
Another thing is, that the index data currently has to be a in datetime which is fine but also has to be named 'timestamp'. You can check this in this example: https://github.com/neurogeriatricskiel/NGMT/blob/main/examples/03a_tutorial_physical_activity_monitoring_with_load.ipynb

Please fix this in the https://github.com/neurogeriatricskiel/NGMT/blob/29586fffbee07ce86345ef3737453536e6bfb21c/ngmt/utils/preprocessing.py#L1004 function

**Comment by masoudabedinifar** [comment]
Hi @JuliusWelzel thanks! I fixed and updated the function and all other files accordingly in 0eb233f2b264ebd7735ebaf25a8686c79e342925 and I am going to close the issue.

**Comment by masoudabedinifar** [comment]
@JuliusWelzel name was changed to time_column_name with commit: f8ef5c41b0310453ad674292b3fc2ea19a8fef19
