### ISSUE TITLE
Issues regarding PhamSittoStandStandtoSitDetection algorithm

### ISSUE THREAD

**Issue by masoudabedinifar** [neurogeriatricskiel/NGMT#74]
Dear all,

The issues that need to be addressed regarding the [PhamSittoStandStandtoSitDetection](https://github.com/neurogeriatricskiel/NGMT/blob/main/ngmt/modules/ssd/_pham.py) algorithm before submitting the JOSS paper could be listed as follows:

1. **Add dt_data as an optional input to the algorithm as we did in [GSD](https://github.com/neurogeriatricskiel/NGMT/blob/main/ngmt/modules/gsd/_paraschiv.py)** 

- [ ]  We need to incorporate "dt_data" into the PhamSittoStandStandtoSitDetection algorithm to provide real-time information whenever it's available and given as an input to the algorithm. The onset and duration also should be updated accordingly.

**Comment by JuliusWelzel** [comment]
Hi, I will take care of that!

**Comment by JuliusWelzel** [comment]
Added in https://github.com/neurogeriatricskiel/NGMT/commit/e5ad5d69e542576dedeac103213e51dc88e74f3f
