### ISSUE TITLE
Add contributing section in README and docs

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/NGMT#76]
As we talked about, we should add a clear instruction on how to contribute to NGMT in the README and the docs as we actively want to support this.
We can maybe follow some steps from [this](https://mne.tools/stable/development/contributing.html) instructions. Imo the guide should read something like:

## Contributing guide
Thanks for considering contributing to our toolbox! NGMT is an open-source project and we welcome contributions from anyone to further enhance this project

There are lots of ways to contribute, such as:

- Use the software, and when you find bugs, tell us about them! We can only fix the bugs we know about.
 - Tell us about parts of the documentation that you find confusing or unclear.
- Tell us about things you wish NGMT could do, or things it can do but you wish they were easier.
- Fix bugs.
- Implement new features.
 - Improve existing tutorials or write new ones.

To report bugs, request new features, or ask about confusing documentation, it’s usually best to open a [new issue](https://github.com/neurogeriatricskiel/NGMT/issues/new/choose)on GitHub. For better reproducibility, be sure to include information about your operating system and NGMT version, and (if applicable) include a reproducible code sample that is as short as possible and ideally uses one of [our example datasets](https://neurogeriatricskiel.github.io/NGMT/datasets/).

### Overview
In general you'll be working with three different copies of the the NGMT codebase: the official remote copy at https://github.com/neurogeriatricskiel/NGMT (usually called ``upstream``), your remote `fork`_ of the upstream repository (similar URL, but with your username in place of ``NGMT``, and usually called ``origin``), and the local copy of the codebase on your computer. The typical contribution process is to:

1. synchronize your local copy with ``upstream``
2. make changes to your local copy
3. `push` your changes to ``origin`` (your remote fork of the upstream)
4. submit a `pull request` from your fork into ``upstream``

### Setting up your local development environment
1. Clone the repository
2. Set up the environment via poetry. (If you don't have poetry, you can install it from [here](https://python-poetry.org/).) Then go to the repository directory, and run ``poetry install``.
3. Make changes to the code
4. Push to your fork
5. Open a Pull request

**Comment by JuliusWelzel** [comment]
@rmndrs89 could you check the last part with setting up the local dev environment? Thanks

**Comment by rmndrs89** [comment]
I have updated the local dev environment section accordingly.

**Comment by JuliusWelzel** [comment]
Thanks, should we add it as a contributing.md to the docs?

**Comment by JuliusWelzel** [comment]
Yes, closing now as team decision 🚀 🔥 ✊
