### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'find' for importer

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/NGMT#77]
The importer for KeepControl allows Path object as [inputs](https://github.com/neurogeriatricskiel/NGMT/blob/da867ab99e6d5b3b402bc989bc10f819a80f1392/ngmt/datasets/keepcontrol.py#L27) but uses a find right in the [beginning](https://github.com/neurogeriatricskiel/NGMT/blob/da867ab99e6d5b3b402bc989bc10f819a80f1392/ngmt/datasets/keepcontrol.py#L53). 
(https://github.com/neurogeriatricskiel/NGMT/blob/da867ab99e6d5b3b402bc989bc10f819a80f1392/ngmt/datasets/keepcontrol.py#L27
https://github.com/neurogeriatricskiel/NGMT/blob/da867ab99e6d5b3b402bc989bc10f819a80f1392/ngmt/datasets/keepcontrol.py#L53

@rmndrs89, could you please have a look and fix this?

**Comment by rmndrs89** [comment]
Do a check whether `file_name` is a `str` or a `pathlib.Path`, and maybe at the beginning change it so that it is always the same type.

**Comment by JuliusWelzel** [comment]
+1 thanks for the suggestions @rmndrs89. In general we should keep it consistent across the toolbox. I would propose all paths or file names are always pathlib objects.

**Comment by masoudabedinifar** [comment]
Dear @rmndrs89 and @JuliusWelzel  I handled in this way: 4cfcde8b644cc911aedd4c737d45454306f926b2 , could you please check it?
