### ISSUE TITLE
Move REQUIRED_COLUMNS to dataclass definition?

### ISSUE THREAD

**Issue by rmndrs89** [neurogeriatricskiel/NGMT#78]
https://github.com/neurogeriatricskiel/NGMT/blob/d6cbe3793e82d24902247d2426b4eae174f0909c/ngmt/datasets/keepcontrol.py#L8

Should we move this (global) variable to the [ngmt_dataclass.py](https://github.com/neurogeriatricskiel/NGMT/blob/main/ngmt/utils/ngmt_dataclass.py)? It should hold across all datasets, and is not specific to [keepcontrol](https://github.com/neurogeriatricskiel/NGMT/blob/main/ngmt/datasets/keepcontrol.py) in my view?

**Comment by JuliusWelzel** [comment]
+1 in favor of this!

**Comment by rmndrs89** [comment]
REQUIRED_COLUMNS has been moved to utils/ngmt_dataclasses.py, the `validate_channels` method has been update accordingly, and `REQUIRED_COLUMNS` is now loaded with an import in the `datasets/keepcontrol.py` script.
