### ISSUE TITLE
Link to public datasets

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/NGMT#79]
Dear all,

in the [contributing guide](https://neurogeriatricskiel.github.io/NGMT/contributing/#contributing-guide) we specifically ask if contributions can be made with the inbuild datasets. The links on the [docs for datasets](https://neurogeriatricskiel.github.io/NGMT/datasets/) only point to the main websites of the projects. Are there freely available datasets which we can link?

@rmndrs89 & @hansencl

**Comment by rmndrs89** [comment]
Hi @JuliusWelzel,

I have updated the dataset descriptions accordingly. For the FAIR-PARK data, there is no such data available.

BR,
Robbin
