### ISSUE TITLE
Unification of toolbox name

### ISSUE THREAD

**Issue by rmndrs89** [neurogeriatricskiel/NGMT#81]
Hi @JuliusWelzel and @masoudabedinifar,

we should also start thinking about unifying the namegiving of our toolbox and variables defined within.

With regards to the toolbox, is it **NeuroGeriatric Motion Toolbox** or **NeuroGeriatrics Motion Toolbox**?

Note that the site name is the latter:
https://github.com/neurogeriatricskiel/NGMT/blob/36ed01e250e593ca3dae11aeeb7d3a2688e67344/mkdocs.yml#L1C12-L1C40

whereas in the main text it is the first.

My suggestion is to use **NeuroGeriatrics Motion Toolbox**, because then **Neurogeriatrics** refers to the name of our research group. In contrast, **Neurogeriatric Motion Toolbox** suggests (imo) that we only consider neurogeriatric motion, although we also process motion of healthy volunteers.

Best regards,
Robbin

**Comment by JuliusWelzel** [comment]
Thanks for raising this, I am +1 for NeuroGeriatric**s** Motion Toolbox

**Comment by masoudabedinifar** [comment]
Thanks @rmndrs89, +1 for NeuroGeriatric**s** Motion Toolbox

**Comment by JuliusWelzel** [comment]
fixed in https://github.com/neurogeriatricskiel/NGMT/commit/60e1402fb5421dc7aafdceca918410a9b23138f6
