### ISSUE TITLE
Update needed for handling non-existent tracked points in importers

### ISSUE THREAD

**Issue by masoudabedinifar** [neurogeriatricskiel/NGMT#86]
Dear @rmndrs89 and @JuliusWelzel,

Following our discussion with @rmndrs89, it's been brought to our attention that there's a need to address the case where the input tracked_points do not exist in the list when using importers. Currently, there's a suggestion to issue a warning and return empty pandas.DataFrame for both data and channels, as drafted [here](https://github.com/neurogeriatricskiel/NGMT/blob/sensepark-data-importer/ngmt/utils/importers.py#L114).
We may need to discuss alternative suggestions on how to handle this case.

Best,
Masoud.

**Comment by JuliusWelzel** [comment]
According with BIDS, if you specify data you have to provide a label for a tracked point:
https://bids-specification.readthedocs.io/en/stable/modality-specific-files/motion.html#channels-description-_channelstsv

I am happy if we return a warning, not an error saying we recommend specifying a label for the tracked point or points of that data that has been imported.

**Comment by rmndrs89** [comment]
Hi @JuliusWelzel ,

I think you misunderstood the issue here.

Suppose that you have data from "LowerBack", "LeftFoot", "RightFoot".

```python
data, channels = mydata.load_recording(file_name, tracked_points=["LowerBack"])
```
should return the data and channels for the "LowerBack"-worn IMU.

But what happens when we do:
```python
data, channels = mydata.load_recording(file_name, tracked_points=["Pelvis"])
```

Should we raise a `ValueError` saying that "Pelvis" tracked point does not exist, or raise a warning and still return an empty dataframe?

What if we do?
```python
data, channels = mydata.load_recording(file_name, tracked_points=["Pelvis", "LeftFoot", "RightFoot"])
```
Should we raise a `ValueError` saying that "Pelvis" tracked point does not exist, or raise a warning and still return a dataframe for the valid tracked points (here, "LeftFoot", "RightFoot")?

**Comment by JuliusWelzel** [comment]
Sorry for the misunderstanding. Tracked point in the importers I wrote is used to label the data you are loading as it has no label in the raw file.

For the cases @rmndrs89 described, I would return an Error when only "invalid" tracked points are used, and a Warning if the list contains one or more invalid tracked points.

What do you think?

**Comment by masoudabedinifar** [comment]
Based on our discussion, I updated the APDM Mobility Lab importer to raise an error when invalid tracked points are entered. You may see the changes in this commit in the sense-park-data-importer branch as: 
[Track invalid tracked points](https://github.com/neurogeriatricskiel/NGMT/blob/sensepark-data-importer/ngmt/utils/importers.py#L114).

Once you approve, we may close the issue.

Kind regard,
Masoud.

**Comment by JuliusWelzel** [comment]
fixed in https://github.com/neurogeriatricskiel/NGMT/pull/87
